### ISSUE TITLE
Loading old gates DB

### ISSUE THREAD

**Issue by Bagu** [bukkitcommons/StarGate-Reremake#2]
Hello,

Is there a way to recover my old gates database ?
Because, if i try to use it, i get these messages : 
```
26/01/2020 11:23:26 [WARN] java.lang.IllegalArgumentException: Invalid UUID string: BaguFr
26/01/2020 11:23:26 [WARN] 	at java.util.UUID.fromString(Unknown Source)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Portal.loadAllGates(Portal.java:1235)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Stargate.reloadGates(Stargate.java:147)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Stargate.onEnable(Stargate.java:95)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
26/01/2020 11:23:26 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
26/01/2020 11:23:26 [WARN] 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
26/01/2020 11:23:26 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
26/01/2020 11:23:26 [WARN] 	at java.lang.Thread.run(Unknown Source)
26/01/2020 11:23:26 [ERROR] Exception while reading stargates from world.db: 1
26/01/2020 11:23:26 [WARN] java.lang.IllegalArgumentException: Invalid UUID string: Cloclo144
26/01/2020 11:23:26 [WARN] 	at java.util.UUID.fromString(Unknown Source)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Portal.loadAllGates(Portal.java:1235)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Stargate.reloadGates(Stargate.java:147)
26/01/2020 11:23:26 [WARN] 	at com.RkCraft.Stargate.Stargate.onEnable(Stargate.java:95)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
26/01/2020 11:23:26 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
26/01/2020 11:23:27 [WARN] 	at java.lang.Thread.run(Unknown Source)
26/01/2020 11:23:27 [ERROR] Exception while reading stargates from world_nether.db: 1
26/01/2020 11:23:27 [WARN] java.lang.IllegalArgumentException: Invalid UUID string: Cloclo144
26/01/2020 11:23:27 [WARN] 	at java.util.UUID.fromString(Unknown Source)
26/01/2020 11:23:27 [WARN] 	at com.RkCraft.Stargate.Portal.loadAllGates(Portal.java:1235)
26/01/2020 11:23:27 [WARN] 	at com.RkCraft.Stargate.Stargate.reloadGates(Stargate.java:147)
26/01/2020 11:23:27 [WARN] 	at com.RkCraft.Stargate.Stargate.onEnable(Stargate.java:95)
26/01/2020 11:23:27 [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
26/01/2020 11:23:27 [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
26/01/2020 11:23:27 [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
26/01/2020 11:23:27 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
26/01/2020 11:23:27 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
26/01/2020 11:23:27 [WARN] 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
26/01/2020 11:23:27 [WARN] 	at java.lang.Thread.run(Unknown Source)
26/01/2020 11:23:27 [ERROR] Exception while reading stargates from world_the_end.db: 1
```

May i replace every User Name by their UUID ?

**Comment by Bagu** [comment]
Ok, replacing name by thier UUID work well.
